export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";

export default [FETCH_USERS_PENDING, FETCH_USERS_SUCCESS, FETCH_USERS_FAILURE];
