export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export default [UPDATE_USER_FAILURE, UPDATE_USER_PENDING, UPDATE_USER_SUCCESS];
